### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by perploug**
Updates all affected dependencies (except for x-ray) to latest secure version. The underlying license-lookup package has also been updated. 

Fixes issue: #23

### CODE REVIEW

**Comment by perploug** [comment]
👍

**Comment by fokusferit** [comment]
👍

**Comment by perploug** [comment]
Hmm - so CDP really does not like npm dependencies which uses a git url.. git not present at path - seen this before @fokusferit ?

**Comment by fokusferit** [comment]
No, but it could be that the ubuntu VM is not allowed to access directly the internet, e.g. it uses internal Nexus and Maven to get all dependencies. Maybe they have some special proxies running there.

The first idea to fix that (might not be the best):

to load that repo via Docker manually and use `npm link` ?

**Comment by perploug** [comment]
👍

**Comment by perploug** [comment]
@fokusferit - okey build is fixed, as the original project is not maintained I forked it and published the fork on npm.

**Comment by fokusferit** [comment]
👍

**Comment by perploug** [comment]
@fokusferit - had to do a merge with master - so here we go again :(

**Comment by perploug** [comment]
👍

**Comment by harti2006** [comment]
:+1:

**Pull request merged**
